---
- name: Fix machineconfg on crc
  hosts: crc
  tasks:
    - name: Read kubelet file
      become: true
      ansible.builtin.shell: |
        cat /var/lib/kubelet/config.json
      register: _config_json
      changed_when: false

    - name: Create machineconfig manifest to overwrite config.json
      ansible.builtin.copy:
        content: |
          apiVersion: machineconfiguration.openshift.io/v1
          kind: MachineConfig
          metadata:
            labels:
              machineconfiguration.openshift.io/role: {{ item }}
            name: 99-overwrite-kubelet-config-{{ item }}
          spec:
            config:
              ignition:
                version: 3.4.0
              storage:
                files:
                - contents:
                    source: data:,{{ _config_json.stdout | urlencode }}
                  mode: 384
                  overwrite: true
                  path: /var/lib/kubelet/config.json
        dest: /tmp/mc-{{ item }}.yaml
      loop:
        - master
        - worker

    - name: Apply machineconfig manifest
      ansible.builtin.command: oc apply -f /tmp/mc-{{ item }}.yaml
      changed_when: false
      loop:
        - master
        - worker

- name: "Run ci/playbooks/edpm/run.yml"
  hosts: "{{ cifmw_zuul_target_host | default('all') }}"
  gather_facts: true
  tasks:
    - name: Filter out host if needed
      when:
        - cifmw_zuul_target_host is defined
        - cifmw_zuul_target_host != 'all'
        - inventory_hostname != cifmw_zuul_target_host
      ansible.builtin.meta: end_host

    - name: Check for edpm-ansible.yml file
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/ci-framework-data/artifacts/edpm-ansible.yml"
      register: edpm_file

    - name: Run Podified EDPM deployment
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook deploy-edpm.yml
          -i "{{ ansible_user_dir }}/ci-framework-data/artifacts/zuul_inventory.yml"
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/edpm_ci.yml
          {%- if edpm_file.stat.exists %}
          -e @{{ ansible_user_dir }}/ci-framework-data/artifacts/edpm-ansible.yml
          {%- endif %}
          {%- if cifmw_extras is defined %}
          {%-   for extra_var in cifmw_extras %}
          -e "{{   extra_var }}"
          {%-   endfor %}
          {%- endif %}
          -e "@{{ ansible_user_dir }}/ci-framework-data/artifacts/parameters/zuul-params.yml"
